"""update_component_feature_flag_unique_index_to_include_usage_location

Revision ID: 00a33b44063e
Revises: 985dab50469d
Create Date: 2025-11-09 18:59:19.309943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00a33b44063e'
down_revision: Union[str, Sequence[str], None] = '985dab50469d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_component_feature_flag_unique'), table_name='component_feature_flags')
    op.create_index('idx_component_feature_flag_unique', 'component_feature_flags', ['component_id', 'feature_flag_id', 'usage_location'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_component_feature_flag_unique', table_name='component_feature_flags')
    op.create_index(op.f('idx_component_feature_flag_unique'), 'component_feature_flags', ['component_id', 'feature_flag_id'], unique=True)
    # ### end Alembic commands ###
