"""add_hook_feature_flags_table

Revision ID: 29c32fe13d01
Revises: da651e0265d1
Create Date: 2025-11-09 17:49:39.828656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29c32fe13d01'
down_revision: Union[str, Sequence[str], None] = 'da651e0265d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hook_feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hook_id', sa.Integer(), nullable=False),
    sa.Column('feature_flag_id', sa.Integer(), nullable=False),
    sa.Column('usage_pattern', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hook_id'], ['hooks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hook_feature_flag_hook', 'hook_feature_flags', ['hook_id'], unique=False)
    op.create_index('idx_hook_feature_flag_flag', 'hook_feature_flags', ['feature_flag_id'], unique=False)
    op.create_index('idx_hook_feature_flag_unique', 'hook_feature_flags', ['hook_id', 'feature_flag_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_hook_feature_flag_unique', table_name='hook_feature_flags')
    op.drop_index('idx_hook_feature_flag_flag', table_name='hook_feature_flags')
    op.drop_index('idx_hook_feature_flag_hook', table_name='hook_feature_flags')
    op.drop_table('hook_feature_flags')
    # ### end Alembic commands ###
