"""add_container_metadata_to_component_feature_flags

Revision ID: 363cabf03aa1
Revises: 29c32fe13d01
Create Date: 2025-11-09 18:32:08.560843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '363cabf03aa1'
down_revision: Union[str, Sequence[str], None] = '29c32fe13d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar usage_location con default 'component' y actualizar registros existentes
    op.add_column('component_feature_flags', sa.Column('usage_location', sa.String(), server_default='component', nullable=True))
    # Actualizar registros existentes para que tengan 'component' como valor
    op.execute("UPDATE component_feature_flags SET usage_location = 'component' WHERE usage_location IS NULL")
    
    op.add_column('component_feature_flags', sa.Column('usage_context', sa.String(), nullable=True))
    op.add_column('component_feature_flags', sa.Column('container_file_path', sa.String(), nullable=True))
    op.add_column('component_feature_flags', sa.Column('usage_type', sa.String(), nullable=True))
    op.add_column('component_feature_flags', sa.Column('combined_with', sa.JSON(), nullable=True))
    op.add_column('component_feature_flags', sa.Column('logic', sa.String(), nullable=True))
    op.create_index('idx_component_feature_flag_container', 'component_feature_flags', ['container_file_path'], unique=False)
    op.create_index('idx_component_feature_flag_location', 'component_feature_flags', ['usage_location'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_component_feature_flag_location', table_name='component_feature_flags')
    op.drop_index('idx_component_feature_flag_container', table_name='component_feature_flags')
    op.drop_column('component_feature_flags', 'logic')
    op.drop_column('component_feature_flags', 'combined_with')
    op.drop_column('component_feature_flags', 'usage_type')
    op.drop_column('component_feature_flags', 'container_file_path')
    op.drop_column('component_feature_flags', 'usage_context')
    op.drop_column('component_feature_flags', 'usage_location')
    # ### end Alembic commands ###
