"""add barrel exports table

Revision ID: 603bed8ade76
Revises: 00a33b44063e
Create Date: 2025-11-10 11:28:51.614377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '603bed8ade76'
down_revision: Union[str, Sequence[str], None] = '00a33b44063e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barrel_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('directory_path', sa.String(), nullable=False),
    sa.Column('index_file_path', sa.String(), nullable=False),
    sa.Column('exported_component_id', sa.Integer(), nullable=True),
    sa.Column('exported_name', sa.String(), nullable=True),
    sa.Column('source_file_path', sa.String(), nullable=False),
    sa.Column('is_container', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exported_component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_barrel_component', 'barrel_exports', ['exported_component_id'], unique=False)
    op.create_index('idx_barrel_directory', 'barrel_exports', ['directory_path'], unique=False)
    op.create_index('idx_barrel_project', 'barrel_exports', ['project_id'], unique=False)
    op.create_index('idx_barrel_unique', 'barrel_exports', ['project_id', 'directory_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_barrel_unique', table_name='barrel_exports')
    op.drop_index('idx_barrel_project', table_name='barrel_exports')
    op.drop_index('idx_barrel_directory', table_name='barrel_exports')
    op.drop_index('idx_barrel_component', table_name='barrel_exports')
    op.drop_table('barrel_exports')
    # ### end Alembic commands ###
