"""Add Hook table and update Component hooks fields

Revision ID: 722758e66f23
Revises: 001
Create Date: 2025-10-28 22:06:36.385256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '722758e66f23'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('hook_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('return_type', sa.String(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('imports', sa.JSON(), nullable=True),
    sa.Column('exports', sa.JSON(), nullable=True),
    sa.Column('native_hooks_used', sa.JSON(), nullable=True),
    sa.Column('custom_hooks_used', sa.JSON(), nullable=True),
    sa.Column('jsdoc', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hooks_name', 'hooks', ['name'], unique=False)
    op.create_index('idx_hooks_project', 'hooks', ['project_id'], unique=False)
    op.create_index('idx_hooks_unique', 'hooks', ['name', 'project_id', 'file_path'], unique=True)
    op.add_column('components', sa.Column('native_hooks_used', sa.JSON(), nullable=True))
    op.add_column('components', sa.Column('custom_hooks_used', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('idx_components_unique'), 'components', type_='unique')
    op.create_index('idx_components_unique', 'components', ['name', 'project_id', 'file_path'], unique=True)
    op.drop_column('components', 'hooks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('hooks', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.drop_index('idx_components_unique', table_name='components')
    op.create_unique_constraint(op.f('idx_components_unique'), 'components', ['name', 'project_id', 'file_path'], postgresql_nulls_not_distinct=False)
    op.drop_column('components', 'custom_hooks_used')
    op.drop_column('components', 'native_hooks_used')
    op.drop_index('idx_hooks_unique', table_name='hooks')
    op.drop_index('idx_hooks_project', table_name='hooks')
    op.drop_index('idx_hooks_name', table_name='hooks')
    op.drop_table('hooks')
    # ### end Alembic commands ###
