"""add_container_file_path_to_components

Revision ID: 985dab50469d
Revises: 363cabf03aa1
Create Date: 2025-11-09 18:33:16.513777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985dab50469d'
down_revision: Union[str, Sequence[str], None] = '363cabf03aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('container_file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'container_file_path')
    # ### end Alembic commands ###
