"""add_component_dependencies_table_and_component_imports

Revision ID: d08976815002
Revises: 722758e66f23
Create Date: 2025-11-08 17:25:53.916883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd08976815002'
down_revision: Union[str, Sequence[str], None] = '722758e66f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('component_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_component_id', sa.Integer(), nullable=True),
    sa.Column('depends_on_name', sa.String(), nullable=False),
    sa.Column('from_path', sa.String(), nullable=False),
    sa.Column('import_type', sa.String(), nullable=False),
    sa.Column('is_external', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depends_on_component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dependency_component', 'component_dependencies', ['component_id'], unique=False)
    op.create_index('idx_dependency_depends_on', 'component_dependencies', ['depends_on_component_id'], unique=False)
    op.create_index('idx_dependency_project', 'component_dependencies', ['project_id'], unique=False)
    op.create_index('idx_dependency_unique', 'component_dependencies', ['component_id', 'depends_on_component_id', 'depends_on_name'], unique=True)
    op.add_column('components', sa.Column('component_imports', postgresql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('components', 'component_imports')
    op.drop_index('idx_dependency_unique', table_name='component_dependencies')
    op.drop_index('idx_dependency_project', table_name='component_dependencies')
    op.drop_index('idx_dependency_depends_on', table_name='component_dependencies')
    op.drop_index('idx_dependency_component', table_name='component_dependencies')
    op.drop_table('component_dependencies')
    # ### end Alembic commands ###
