"""Add feature flags tables

Revision ID: da651e0265d1
Revises: d08976815002
Create Date: 2025-11-08 22:38:11.599678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'da651e0265d1'
down_revision: Union[str, Sequence[str], None] = 'd08976815002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('possible_values', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feature_flags_name', 'feature_flags', ['name'], unique=False)
    op.create_index('idx_feature_flags_project', 'feature_flags', ['project_id'], unique=False)
    op.create_index('idx_feature_flags_unique', 'feature_flags', ['name', 'project_id'], unique=True)
    op.create_table('component_feature_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('feature_flag_id', sa.Integer(), nullable=False),
    sa.Column('usage_pattern', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_component_feature_flag_component', 'component_feature_flags', ['component_id'], unique=False)
    op.create_index('idx_component_feature_flag_flag', 'component_feature_flags', ['feature_flag_id'], unique=False)
    op.create_index('idx_component_feature_flag_unique', 'component_feature_flags', ['component_id', 'feature_flag_id'], unique=True)
    op.alter_column('component_dependencies', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('component_dependencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('component_dependencies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('component_dependencies', 'is_external',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_component_feature_flag_unique', table_name='component_feature_flags')
    op.drop_index('idx_component_feature_flag_flag', table_name='component_feature_flags')
    op.drop_index('idx_component_feature_flag_component', table_name='component_feature_flags')
    op.drop_table('component_feature_flags')
    op.drop_index('idx_feature_flags_unique', table_name='feature_flags')
    op.drop_index('idx_feature_flags_project', table_name='feature_flags')
    op.drop_index('idx_feature_flags_name', table_name='feature_flags')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###
